### ISSUE TITLE
Unable to Run in Dev

### ISSUE THREAD

**Issue by willpuckett** [denoland/deno_blog#149]
It seems that the url being returned by `callsites()[1].getFileName()` in `blog.tsx:109` doesn't include the 'file://', and is preventing `fromFileUrl` from parsing it correctly...

```
deno task start
Task start deno run --allow-net --allow-read --allow-env --watch main.tsx --dev
Watcher Process started.
⚠️  Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.

import emojis from "./all.json" assert { type: "json" };

  at https://deno.land/x/emoji@0.3.0/emoji.ts:2:1

TypeError: Invalid URL: '/Users/puck/Public/smote/main.tsx'
    at getSerialization (ext:deno_url/00_url.js:98:11)
    at new URL (ext:deno_url/00_url.js:405:27)
    at fromFileUrl (https://deno.land/std@0.193.0/path/posix.ts:460:36)
    at configureBlog (https://raw.githubusercontent.com/denoland/deno_blog/main/blog.tsx:176:22)
    at blog (https://raw.githubusercontent.com/denoland/deno_blog/main/blog.tsx:110:27)
    at file:///Users/puck/Public/smote/main.tsx:11:1
error: Uncaught (in promise) Error: Cannot run blog from a remote URL.
    throw new Error("Cannot run blog from a remote URL.");
          ^
    at configureBlog (https://raw.githubusercontent.com/denoland/deno_blog/main/blog.tsx:180:11)
    at blog (https://raw.githubusercontent.com/denoland/deno_blog/main/blog.tsx:110:27)
    at file:///Users/puck/Public/smote/main.tsx:11:1
Watcher Process failed. Restarting on file change...
^C
```

**Comment by willpuckett** [comment]
denoland/deno#24727

**Comment by willpuckett** [comment]
I made a few [changes](https://github.com/willpuckett/deno_blog) that seem to work on my machine, although I'm not sure they're fully inclusive of handling paths on all platforms...

**Comment by san-ghun** [comment]
> I made a few changes in #150 that seem to work on my machine and Deno Deploy, although I'm not sure they're fully inclusive of handling paths on all platforms...

Hey @willpuckett 
I have faced the same issue. I am unable to run it on local dev. With your change on #150 fixed mine to be able to run in local dev. Thanks!

**Comment by tdharris** [comment]
I also ran into this issue. I'm hoping this will be considered for fix in `main`. Otherwise, the latest compatible version of Deno is `1.45.3`

**Comment by tdharris** [comment]
This also started failing in PROD in Deno Deploy. The same fix appears to work. Likely depends on the version of Deno in the runtime. If it's newer than `1.45.3` then it will fail and requires that `file://` prefix you have from #150.

**Comment by ryoo14** [comment]
I am also encountering the same issue. 
I am using macOS, and the same issue occurs not only with `deno run dev` but also with `deno run serve`.

**Comment by aryan02420** [comment]
[Deno Deploy has rolled back the changes that caused this error](https://github.com/denoland/deploy_feedback/issues/724#issuecomment-2395381000). For local development, I am using v1.44, which is working perfectly.

**Comment by AlperRehaYAZGAN** [comment]
This repository latest main branch commit works fine but it has not got release matched yet. So You need to import it from pointing commit name to run in development mode.   

1. You need to update "main.tsx" file like this:  
```javascript
/** @jsx h */

import blog, { ga, redirects, h } from "blog";
```   
  
2.  You need to point import of "blog" the correct commit in deno.json (This setup works for my setup "deno 2.1.4 (stable, release, aarch64-apple-darwin)"):  
Commit: `https://raw.githubusercontent.com/denoland/deno_blog/589c4750d001ae2a4e921385be558d97060e3933/blog.tsx`.   
And if you are using "deno v2" its better to update gfm@0.2.5 to gfm@0.10.0 to support v2 like below.   

```json
"imports": {
    "blog": "https://raw.githubusercontent.com/denoland/deno_blog/589c4750d001ae2a4e921385be558d97060e3933/blog.tsx",
    "https://deno.land/x/gfm@0.2.5/mod.ts": "jsr:@deno/gfm@^0.10.0"
}
```

4. Also you need to tell deno to you can import from "github.com" instead of "deno.land/x" to get from commit. Update deno.json dev task command **"--allow-import"**:   
```json
{
     "dev": "deno run --allow-net --allow-read --allow-import --allow-env --watch main.tsx --dev",
}
```

It worked for me and my blog site on link https://yazganxyz-rehash-blog.deno.dev/ 

Have a good day 🔥.
